# -*- coding: utf-8 -*-
"""
Created on Fri Jan 23 13:38:40 2026

@author: aengstrom
"""

from enum import StrEnum

# --- Human-readable names ---
class CompoundName(StrEnum):
    C_ETHANE = "Ethane"
    C_ETHYLENE = "Ethylene"
    C_PROPANE = "Propane"
    C_PROPYLENE = "Propylene"
    C_ISO_BUTANE = "Iso-butane"
    C_N_BUTANE = "N-butane"
    C_ACETYLENE = "Acetylene"
    C_TRANS_2_BUTENE = "Trans-2-butene"
    C_1_BUTENE = "1-butene"
    C_CIS_2_BUTENE = "Cis-2-butene"
    C_CYCLOPENTANE = "Cyclopentane"
    C_ISO_PENTANE = "Iso-pentane"
    C_N_PENTANE = "N-pentane"
    C_1_3_BUTADIENE = "1,3-butadiene"
    C_TRANS_2_PENTENE = "Trans-2-pentene"
    C_1_PENTENE = "1-pentene"
    C_CIS_2_PENTENE = "Cis-2-pentene"
    C_2_2_DIMETHYLBUTANE = "2,2-dimethylbutane"
    C_2_3_DIMETHYLBUTANE = "2,3-dimethylbutane"
    C_2_METHYLPENTANE = "2-methylpentane"
    C_3_METHYLPENTANE = "3-methylpentane"
    C_ISOPRENE = "Isoprene"
    C_2_METHYL_1_PENTENE = "2-methyl-1-pentene"
    C_1_HEXENE = "1-hexene"
    C_N_HEXANE = "N-hexane"
    C_METHYLCYCLOPENTANE = "Methylcyclopentane"
    C_2_4_DIMETHYLPENTANE = "2,4-dimethylpentane"
    C_BENZENE = "Benzene"
    C_CYCLOHEXANE = "Cyclohexane"
    C_2_METHYLHEXANE = "2-methylhexane"
    C_2_3_DIMETHYLPENTANE = "2,3-dimethylpentane"
    C_3_METHYLHEXANE = "3-methylhexane"
    C_2_2_4_TRIMETHYLPENTANE = "2,2,4-trimethylpentane"
    C_N_HEPTANE = "N-heptane"
    C_METHYLCYCLOHEXANE = "Methylcyclohexane"
    C_2_3_4_TRIMETHYLPENTANE = "2,3,4-trimethylpentane"
    C_TOLUENE = "Toluene"
    C_2_METHYLHEPTANE = "2-methylheptane"
    C_3_METHYLHEPTANE = "3-methylheptane"
    C_N_OCTANE = "N-octane"
    C_ETHYLBENZENE = "Ethylbenzene"
    C_M_P_XYLENE = "M&p-xylene"
    C_STYRENE = "Styrene"
    C_O_XYLENE = "O-xylene"
    C_N_NONANE = "N-nonane"
    C_ISO_PROPYLBENZENE = "Iso-propylbenzene"
    C_ALPHA_PINENE = "Alpha-pinene"
    C_N_PROPYLBENZENE = "N-propylbenzene"
    C_M_ETHYLTOLUENE = "M-ethyltoluene"
    C_P_ETHYLTOLUENE = "P-ethyltoluene"
    C_1_3_5_TRI_M_BENZENE = "1,3,5-tri-m-benzene"
    C_O_ETHYLTOLUENE = "O-ethyltoluene"
    C_BETA_PINENE = "Beta-pinene"
    C_1_2_4_TRI_M_BENZENE = "1,2,4-tri-m-benzene"
    C_N_DECANE = "N-decane"
    C_1_2_3_TRI_M_BENZENE = "1,2,3-tri-m-benzene"
    C_M_DIETHYLBENZENE = "M-diethylbenzene"
    C_P_DIETHYLBENZENE = "P-diethylbenzene"
    C_N_UNDECANE = "N-undecane"
    C_N_DODECANE = "N-dodecane"
    C_TNMTC = "TNMTC"
    C_TNMHC = "TNMHC"