# -*- coding: utf-8 -*-
"""
AQS qualifier code registry for AutoGC validation.

Each entry in QUALIFIER_CODES maps a code string to a QualifierCodeInfo
NamedTuple with two fields:

  description  Human-readable meaning of the code.
  is_null      True  → the code nullifies (invalidates) data.
               False → the code flags data without nullifying it.

NULL_CODES is a frozenset of all codes where is_null is True, derived
automatically from QUALIFIER_CODES — no need to maintain it separately.

Add new codes to QUALIFIER_CODES; everything else updates automatically.
"""

from typing import NamedTuple


class QualifierCodeInfo(NamedTuple):
    description: str
    is_null: bool


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------
QUALIFIER_CODES: dict[str, QualifierCodeInfo] = {
    # ── Null codes (data invalidated) ──────────────────────────────────────
    "AC": QualifierCodeInfo("Construction/Repairs in Area",                                           True),
    "AD": QualifierCodeInfo("Shelter Storm Damage",                                                   True),
    "AE": QualifierCodeInfo("Shelter Temperature Outside Limits",                                     True),
    "AF": QualifierCodeInfo("Scheduled but not Collected",                                            True),
    "AG": QualifierCodeInfo("Sample Time Out of Limits",                                              True),
    "AH": QualifierCodeInfo("Sample Flow Rate Out of Limits",                                         True),
    "AI": QualifierCodeInfo("Insufficient Data (cannot calculate)",                                   True),
    "AM": QualifierCodeInfo("Miscellaneous Void",                                                     True),
    "AN": QualifierCodeInfo("Machine Malfunction",                                                    True),
    "AP": QualifierCodeInfo("Vandalism",                                                              True),
    "AQ": QualifierCodeInfo("Collection Error",                                                       True),
    "AR": QualifierCodeInfo("Lab Error",                                                              True),
    "AS": QualifierCodeInfo("Poor Quality Assurance Results",                                         True),
    "AT": QualifierCodeInfo("Calibration",                                                            True),
    "AU": QualifierCodeInfo("Monitoring Waived",                                                      True),
    "AV": QualifierCodeInfo("Power Failure",                                                          True),
    "AW": QualifierCodeInfo("Wildlife Damage",                                                        True),
    "AX": QualifierCodeInfo("Precision Check",                                                        True),
    "AY": QualifierCodeInfo("QC Control Points (zero/span)",                                          True),
    "AZ": QualifierCodeInfo("QC Audit",                                                               True),
    "BA": QualifierCodeInfo("Maintenance / Routine Repairs",                                          True),
    "BB": QualifierCodeInfo("Unable to Reach Site",                                                   True),
    "BE": QualifierCodeInfo("Building / Site Repair",                                                 True),
    "BH": QualifierCodeInfo("Interference/co-elution/misidentification",                              True),
    "BI": QualifierCodeInfo("Lost or Damaged in Transit",                                             True),
    "BJ": QualifierCodeInfo("Operator Error",                                                         True),
    "BK": QualifierCodeInfo("Site Computer / Data Logger Down",                                       True),
    "BL": QualifierCodeInfo("QA Audit",                                                               True),
    "DA": QualifierCodeInfo("Aberrant Data (Corrupt Files, Aberrant Chromatography, Spikes, Shifts)", True),
    "DL": QualifierCodeInfo("Detection Limit",                                                        True),
    "MB": QualifierCodeInfo("Method Blank (Analytical)",                                              True),
    "MC": QualifierCodeInfo("Module End Cap Missing",                                                 True),
    # "SC": QualifierCodeInfo("...", True),  # paste cut off — add when known

    # ── Flag codes (data flagged but not nullified) ────────────────────────
    # Internal codes generated by the AutoGC validation software:
    "LB":   QualifierCodeInfo("Blank above MDL",                                                      False),
    "LL":   QualifierCodeInfo("Calibrant recovery below lower bound",                                 False),
    "LK":   QualifierCodeInfo("Calibrant recovery above upper bound",                                 False),
    "QX":   QualifierCodeInfo("Does not Meet QC Criteria",                                            False),
    # AQS standard qualifier codes (col1 values; col3 type label = "QA"):
    "1":    QualifierCodeInfo("Deviation from a CFR/Critical Criteria Requirement",                   False),
    "1V":   QualifierCodeInfo("Data reviewed and validated",                                          False),
    "2":    QualifierCodeInfo("Operational Deviation",                                                False),
    "3":    QualifierCodeInfo("Field Issue",                                                          False),
    "4":    QualifierCodeInfo("Lab Issue",                                                            False),
    "5":    QualifierCodeInfo("Outlier",                                                              False),
    "6":    QualifierCodeInfo("QAPP Issue",                                                           False),
    "7":    QualifierCodeInfo("Below Lowest Calibration Level",                                       False),
    "DI":   QualifierCodeInfo("Sample was Diluted for Analysis",                                      False),
    "EH":   QualifierCodeInfo("Estimated; Exceeds Upper Range",                                       False),
    "FB":   QualifierCodeInfo("Field Blank Value Above Acceptable Limit",                             False),
    "HT":   QualifierCodeInfo("Sample Pick-up Hold Time Exceeded",                                    False),
    "LJ":   QualifierCodeInfo("Identification of Analyte is Acceptable; Reported Value is an Estimate", False),
    "MD":   QualifierCodeInfo("Value Less Than MDL",                                                  False),
    "ND":   QualifierCodeInfo("No Value Detected",                                                    False),
    "NS":   QualifierCodeInfo("Influenced by Nearby Source",                                          False),

    "SQ":   QualifierCodeInfo("Value Between SQL and MDL",                                            False),
    "SS":   QualifierCodeInfo("Value Substituted from Secondary Monitor",                             False),
    "SX":   QualifierCodeInfo("Does Not Meet Siting Criteria",                                        False),
    "TB":   QualifierCodeInfo("Trip Blank Value Above Acceptable Limit",                              False),
    "V":    QualifierCodeInfo("Validated Value",                                                      False),
    "VB":   QualifierCodeInfo("Value Below Normal; No Reason to Invalidate",                          False),
    "XC":   QualifierCodeInfo("Canister Certification Expired",                                       False),
    # paste cut off after XC — add remaining codes when known
}

# Derived automatically — do not edit manually.
NULL_CODES: frozenset[str] = frozenset(
    code for code, info in QUALIFIER_CODES.items() if info.is_null
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def is_null_code(code: str) -> bool:
    """Return True if *code* nullifies (invalidates) data."""
    return code in NULL_CODES


def get_qualifier_description(code: str, default: str = "") -> str:
    """Return the human-readable description for *code*, or *default* if unknown."""
    info = QUALIFIER_CODES.get(code)
    return info.description if info is not None else default
