# -*- coding: utf-8 -*-
"""
Created on Tue Jan 13 13:56:06 2026

@author: aengstrom
"""
VOC_DATA = [
    {"compound": "Ethane", "aqs_code": 43202, "category": "Alkane", "carbon_count": 2, 'molecular_weight': 30.07, 'column': 'PLOT', 'elution_order': 1, 'priority': 1},
    {"compound": "Ethylene", "aqs_code": 43203, "category": "Alkene", "carbon_count": 2, 'molecular_weight': 28.05, 'column': 'PLOT', 'elution_order': 2, 'priority': 1},
    {"compound": "Propane", "aqs_code": 43204, "category": "Alkane", "carbon_count": 3, 'molecular_weight': 44.097, 'column': 'PLOT', 'elution_order': 3, 'priority': 1},
    {"compound": "Propylene", "aqs_code": 43205, "category": "Alkene", "carbon_count": 3, 'molecular_weight': 42.081, 'column': 'PLOT', 'elution_order': 4, 'priority': 1},
    {"compound": "Iso-butane", "aqs_code": 43214, "category": "Alkane", "carbon_count": 4, 'molecular_weight': 58.12, 'column': 'PLOT', 'elution_order': 5, 'priority': 1},
    {"compound": "N-butane", "aqs_code": 43212, "category": "Alkane", "carbon_count": 4, 'molecular_weight': 58.12, 'column': 'PLOT', 'elution_order': 6, 'priority': 1},
    {"compound": "Acetylene", "aqs_code": 43206, "category": "Alkyne", "carbon_count": 2, 'molecular_weight': 26.038, 'column': 'PLOT', 'elution_order': 7, 'priority': 0},
    {"compound": "Trans-2-butene", "aqs_code": 43216, "category": "Alkene", "carbon_count": 4, 'molecular_weight': 56.11, 'column': 'PLOT', 'elution_order': 8, 'priority': 1},
    {"compound": "1-butene", "aqs_code": 43280, "category": "Alkene", "carbon_count": 4, 'molecular_weight': 56.11, 'column': 'PLOT', 'elution_order': 9, 'priority': 1},
    {"compound": "Cis-2-butene", "aqs_code": 43217, "category": "Alkene", "carbon_count": 4, 'molecular_weight': 56.11, 'column': 'PLOT', 'elution_order': 10, 'priority': 1},
    {"compound": "Cyclopentane", "aqs_code": 43242, "category": "Alkane", "carbon_count": 5, 'molecular_weight': 70.13, 'column': 'PLOT', 'elution_order': 11, 'priority': 0},
    {"compound": "Iso-pentane", "aqs_code": 43221, "category": "Alkane", "carbon_count": 5, 'molecular_weight': 72.15, 'column': 'PLOT', 'elution_order': 12, 'priority': 1},
    {"compound": "N-pentane", "aqs_code": 43220, "category": "Alkane", "carbon_count": 5, 'molecular_weight': 72.15, 'column': 'PLOT', 'elution_order': 13, 'priority': 1},
    {"compound": "1,3-butadiene", "aqs_code": 43218, "category": "Alkene", "carbon_count": 4, 'molecular_weight': 54.0916, 'column': 'PLOT', 'elution_order': 14, 'priority': 0},
    {"compound": "Trans-2-pentene", "aqs_code": 43226, "category": "Alkene", "carbon_count": 5, 'molecular_weight': 70.13, 'column': 'PLOT', 'elution_order': 15, 'priority': 0},
    {"compound": "1-pentene", "aqs_code": 43224, "category": "Alkene", "carbon_count": 5, 'molecular_weight': 70.134, 'column': 'PLOT', 'elution_order': 16, 'priority': 0},
    {"compound": "Cis-2-pentene", "aqs_code": 43227, "category": "Alkene", "carbon_count": 5, 'molecular_weight': 70.134, 'column': 'PLOT', 'elution_order': 17, 'priority': 0},
    {"compound": "2,2-dimethylbutane", "aqs_code": 43244, "category": "Alkane", "carbon_count": 6, 'molecular_weight': 86.17, 'column': 'PLOT', 'elution_order': 18, 'priority': 0},
    {"compound": "2,3-dimethylbutane", "aqs_code": 43284, "category": "Alkane", "carbon_count": 6, 'molecular_weight': 86.17, 'column': 'PLOT', 'elution_order': 19, 'priority': 0},
    {"compound": "2-methylpentane", "aqs_code": 43285, "category": "Alkane", "carbon_count": 6, 'molecular_weight': 86.18, 'column': 'PLOT', 'elution_order': 20, 'priority': 0},
    {"compound": "3-methylpentane", "aqs_code": 43230, "category": "Alkane", "carbon_count": 6, 'molecular_weight': 86.18, 'column': 'PLOT', 'elution_order': 21, 'priority': 0},
    {"compound": "Isoprene", "aqs_code": 43243, "category": "Terpene", "carbon_count": 5, 'molecular_weight': 68.12, 'column': 'PLOT', 'elution_order': 22, 'priority': 1},
    {"compound": "2-methyl-1-pentene", "aqs_code": 43246, "category": "Alkene", "carbon_count": 6,'molecular_weight': 84.16, 'column': 'PLOT', 'elution_order': 23, 'priority': 0},
    {"compound": "1-hexene", "aqs_code": 43245, "category": "Alkene", "carbon_count": 6,'molecular_weight':84.1608, 'column': 'PLOT', 'elution_order': 24, 'priority': 0},
    {"compound": "N-hexane", "aqs_code": 43231, "category": "Alkane", "carbon_count": 6,'molecular_weight': 86.17848, 'column': 'BP', 'elution_order': 1, 'priority': 1},
    {"compound": "Methylcyclopentane", "aqs_code": 43262, "category": "Alkane", "carbon_count": 6,'molecular_weight':84.16, 'column': 'BP', 'elution_order': 2, 'priority': 0},
    {"compound": "2,4-dimethylpentane", "aqs_code": 43247, "category": "Alkane", "carbon_count": 7,'molecular_weight': 100.2, 'column': 'BP', 'elution_order': 3, 'priority': 0},
    {"compound": "Benzene", "aqs_code": 45201, "category": "Aromatic", "carbon_count": 6,'molecular_weight':78.11, 'column': 'BP', 'elution_order': 4, 'priority': 1},
    {"compound": "Cyclohexane", "aqs_code": 43248, "category": "Alkane", "carbon_count": 6,'molecular_weight':84.16, 'column': 'BP', 'elution_order': 5, 'priority': 0},
    {"compound": "2-methylhexane", "aqs_code": 43263, "category": "Alkane", "carbon_count": 7,'molecular_weight':100.2, 'column': 'BP', 'elution_order': 6, 'priority': 0},
    {"compound": "2,3-dimethylpentane", "aqs_code": 43291, "category": "Alkane", "carbon_count": 7,'molecular_weight':100.2, 'column': 'BP', 'elution_order': 7, 'priority': 0},
    {"compound": "3-methylhexane", "aqs_code": 43249, "category": "Alkane", "carbon_count": 7,'molecular_weight':100.2, 'column': 'BP', 'elution_order': 8, 'priority': 0},
    {"compound": "2,2,4-trimethylpentane", "aqs_code": 43250, "category": "Alkane", "carbon_count": 8,'molecular_weight':114.23, 'column': 'BP', 'elution_order': 9, 'priority': 1},
    {"compound": "N-heptane", "aqs_code": 43232, "category": "Alkane", "carbon_count": 7,'molecular_weight':100.21, 'column': 'BP', 'elution_order': 10, 'priority': 0},
    {"compound": "Methylcyclohexane", "aqs_code": 43261, "category": "Alkane", "carbon_count": 7,'molecular_weight':98.186, 'column': 'BP', 'elution_order': 11, 'priority': 0},
    {"compound": "2,3,4-trimethylpentane", "aqs_code": 43252, "category": "Alkane", "carbon_count": 8,'molecular_weight':114.23, 'column': 'BP', 'elution_order': 12, 'priority': 0},
    {"compound": "Toluene", "aqs_code": 45202, "category": "Aromatic", "carbon_count": 7,'molecular_weight':92.14, 'column': 'BP', 'elution_order': 13, 'priority': 1},
    {"compound": "2-methylheptane", "aqs_code": 43960, "category": "Alkane", "carbon_count": 8,'molecular_weight':114.23, 'column': 'BP', 'elution_order': 14, 'priority': 0},
    {"compound": "3-methylheptane", "aqs_code": 43253, "category": "Alkane", "carbon_count": 8,'molecular_weight':114.23, 'column': 'BP', 'elution_order': 15, 'priority': 0},
    {"compound": "N-octane", "aqs_code": 43233, "category": "Alkane", "carbon_count": 8,'molecular_weight':114.23, 'column': 'BP', 'elution_order': 16, 'priority': 0},
    {"compound": "Ethylbenzene", "aqs_code": 45203, "category": "Aromatic", "carbon_count": 8,'molecular_weight':106.167, 'column': 'BP', 'elution_order': 17, 'priority': 1},
    {"compound": "M&p-xylene", "aqs_code": 45109, "category": "Aromatic", "carbon_count": 8,'molecular_weight': 106.16, 'column': 'BP', 'elution_order': 18, 'priority': 1},
    {"compound": "Styrene", "aqs_code": 45220, "category": "Aromatic", "carbon_count": 8,'molecular_weight':104.15, 'column': 'BP', 'elution_order': 19, 'priority': 1},
    {"compound": "O-xylene", "aqs_code": 45204, "category": "Aromatic", "carbon_count": 8,'molecular_weight':106.16, 'column': 'BP', 'elution_order': 20, 'priority': 1},
    {"compound": "N-nonane", "aqs_code": 43235, "category": "Alkane", "carbon_count": 9,'molecular_weight':128.2, 'column': 'BP', 'elution_order': 21, 'priority': 0},
    {"compound": "Iso-propylbenzene", "aqs_code": 45210, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 22, 'priority': 0},
    {"compound": "Alpha-pinene", "aqs_code": 43256, "category": "Terpene", "carbon_count": 10,'molecular_weight':136.23, 'column': 'BP', 'elution_order': 23, 'priority': 0},
    {"compound": "N-propylbenzene", "aqs_code": 45209, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.2, 'column': 'BP', 'elution_order': 24, 'priority': 0},
    {"compound": "M-ethyltoluene", "aqs_code": 45212, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 25, 'priority': 1},
    {"compound": "P-ethyltoluene", "aqs_code": 45213, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 26, 'priority': 1},
    {"compound": "1,3,5-tri-m-benzene", "aqs_code": 45207, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 27, 'priority': 0},
    {"compound": "O-ethyltoluene", "aqs_code": 45211, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 28, 'priority': 1},
    {"compound": "Beta-pinene", "aqs_code": 43257, "category": "Terpene", "carbon_count": 10,'molecular_weight':136.23, 'column': 'BP', 'elution_order': 29, 'priority': 0},
    {"compound": "1,2,4-tri-m-benzene", "aqs_code": 45208, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 30, 'priority': 1},
    {"compound": "N-decane", "aqs_code": 43238, "category": "Alkane", "carbon_count": 10,'molecular_weight':142.28, 'column': 'BP', 'elution_order': 31, 'priority': 0},
    {"compound": "1,2,3-tri-m-benzene", "aqs_code": 45225, "category": "Aromatic", "carbon_count": 9,'molecular_weight':120.19, 'column': 'BP', 'elution_order': 32, 'priority': 1},
    {"compound": "M-diethylbenzene", "aqs_code": 45218, "category": "Aromatic", "carbon_count": 10,'molecular_weight':134.22, 'column': 'BP', 'elution_order': 33, 'priority': 0},
    {"compound": "P-diethylbenzene", "aqs_code": 45219, "category": "Aromatic", "carbon_count": 10,'molecular_weight':134.22, 'column': 'BP', 'elution_order': 34, 'priority': 0},
    {"compound": "N-undecane", "aqs_code": 43954, "category": "Alkane", "carbon_count": 11,'molecular_weight':156.31, 'column': 'BP', 'elution_order': 35, 'priority': 0},
    {"compound": "N-dodecane", "aqs_code": 43141, "category": "Alkane", "carbon_count": 12,'molecular_weight':170.34, 'column': 'BP', 'elution_order': 36, 'priority': 0}
]


